### ISSUE TITLE
AggregatedResults.print() crashes when suite filter yields no test cases

### ISSUE THREAD

**Issue by MikeHopcroft** [MikeHopcroft/PrixFixe#90]
Repro
~~~
% node build\samples\test_runner.js ..\mochajava\tests\roadmap.yaml -s=fail
~~~
where there is no suite called "fail".

Result is following exception.
~~~
(node:20364) UnhandledPromiseRejectionWarning: TypeError: computeStatistics: need at least one value.
    at StatisticsAggregator.computeStatistics (D:\git\menubot\shortorder\node_modules\prix-fixe\build\src\test_suite\statistics_aggregator.js:14:19)
    at AggregatedResults.printLatencyStatistics (D:\git\menubot\shortorder\node_modules\prix-fixe\build\src\test_suite\test_suite.js:209:41)
    at AggregatedResults.print (D:\git\menubot\shortorder\node_modules\prix-fixe\build\src\test_suite\test_suite.js:189:14)
    at Object.testRunnerMain (D:\git\menubot\shortorder\node_modules\prix-fixe\build\src\test_suite\test_runner_main.js:152:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:20364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
~~~

**Comment by MikeHopcroft** [comment]
This issue will become more important when we add suite filter expressions.
